In [1]:
from util import *

In [2]:
import numpy as np

#Parameter to create student
n_stud = 20000
prop_gp = [0.4,0.6] #vector gamma in the paper
mean_gp = [0,0]
chi = [2,2] #std of latent qualities of groups

#Parameter of college
n_col = 2 #Number of college
noise_mean = [0,0]
sigma = [2,2] #std of noise of each groups
lambdas = [1,0.5] #cov of noies of each groups
prop_all_g_prefer = [0.4,0.4] #This should be the vector beta in the paper

capacities_rate = [0.2,0.2] #This should be the vector alpha in the paper.
capacities = [int(r * n_stud) for r in capacities_rate]#This vector must have the same length as the number of college, i.e. len(capacities) = n_col. The componenets should be integers

sigma_i = np.sqrt(chi[0]**2 + sigma[0]**2)
sigma_ii = np.sqrt(chi[1]**2 + sigma[1]**2)
cor_i = chi[0]**2/sigma_i**2
cor_ii = chi[1]**2/sigma_ii**2
std_estimated = [np.sqrt(i**2 + j**2) for i,j in zip(chi,sigma)]

In [3]:
simul = simulation(n_stud = n_stud,
                   prop_gp=prop_gp,
                   mean_gp=mean_gp,
                   std_gp = chi,
                   n_col=n_col,
                   noise_mean=noise_mean,
                   noise_std = sigma,
                   noise_cov = lambdas,
                   prop_all_g_prefer=prop_all_g_prefer,
                   capacities_rate=capacities_rate)

In [4]:
simul.create_students()

[array([ 0.75130899, -0.76892244, -0.24943529, ...,  1.56905453,
        -0.34482515, -2.03198628]),
 array([-1.5278379 , -0.31930495,  0.08134665, ...,  2.04996579,
        -2.84922625, -1.82525685])]

In [5]:
simul.create_col_estim_corr_nois()

[array([[ 5.38506362,  6.65149139],
        [ 2.10306378,  1.8443918 ],
        [ 0.96497709, -0.59322929],
        ...,
        [ 0.53518572, -0.67508482],
        [-1.16301546, -1.30490066],
        [-2.57953439, -2.56334289]]),
 array([[-2.48116783, -1.95772526],
        [-0.35102368, -1.37633214],
        [ 2.13209638, -3.47855   ],
        ...,
        [ 5.64740839,  2.66620499],
        [-2.18758091, -2.78005776],
        [-0.64070682, -0.51367409]])]

In [6]:
simul.create_stud_pref_2()

[[[0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],


In [7]:
simul.grades_gr_to_grades_col()

[[[5.385063618823559,
   2.1030637804347307,
   0.9649770948462066,
   -2.8983248324443758,
   -1.938685343091403,
   -0.4076586485883433,
   1.6084983992561148,
   -2.759410617509354,
   0.7041160164720247,
   -0.9013609266352363,
   -0.7680699055942339,
   0.3729093085745736,
   -4.072073317950246,
   8.931110978596259,
   -0.04307620489582398,
   -5.132490628160436,
   0.2348460038175335,
   0.8566619753405408,
   0.9413787188303091,
   1.739657779953775,
   -2.3811408507793956,
   2.388367150636703,
   -2.4169669043075106,
   0.23300906595903345,
   1.496030760145852,
   -3.01875815625119,
   1.101604578903691,
   -3.1183137957456535,
   6.112485001859772,
   -1.585148880080316,
   1.4162197247573696,
   -1.1627511400768205,
   -0.35739082174112546,
   2.3963210413844442,
   2.16387551803016,
   -0.42579430633553916,
   -0.3422211974336641,
   5.937244602363437,
   1.4695302289151821,
   0.0902274675727297,
   -3.4404478709817443,
   1.3556943058521265,
   -3.6499596121974225,
   3

In [8]:
simul.grades_gr_to_grades_col()

[[[5.385063618823559,
   2.1030637804347307,
   0.9649770948462066,
   -2.8983248324443758,
   -1.938685343091403,
   -0.4076586485883433,
   1.6084983992561148,
   -2.759410617509354,
   0.7041160164720247,
   -0.9013609266352363,
   -0.7680699055942339,
   0.3729093085745736,
   -4.072073317950246,
   8.931110978596259,
   -0.04307620489582398,
   -5.132490628160436,
   0.2348460038175335,
   0.8566619753405408,
   0.9413787188303091,
   1.739657779953775,
   -2.3811408507793956,
   2.388367150636703,
   -2.4169669043075106,
   0.23300906595903345,
   1.496030760145852,
   -3.01875815625119,
   1.101604578903691,
   -3.1183137957456535,
   6.112485001859772,
   -1.585148880080316,
   1.4162197247573696,
   -1.1627511400768205,
   -0.35739082174112546,
   2.3963210413844442,
   2.16387551803016,
   -0.42579430633553916,
   -0.3422211974336641,
   5.937244602363437,
   1.4695302289151821,
   0.0902274675727297,
   -3.4404478709817443,
   1.3556943058521265,
   -3.6499596121974225,
   3

In [9]:
solver = solver()

In [10]:
solver.cutoff_solver(simul.objective_bads)

Beginning optimization of a DETERMINISTIC objective function

 Iteration    f-count         f(x)           MeshScale          Method             Actions
     0           2        0.192528               1                                 Uncertainty test
     0           6        0.192528               1         Initial mesh            Initial points
     0          10        0.192528             0.5         Refine grid             Train
     1          11        0.171285             0.5     Incremental search (ES-wcm)        
     1          18        0.171285            0.25         Refine grid             Train
     2          19        0.138996            0.25     Incremental search (ES-ell)        
     2          26        0.138996           0.125         Refine grid             
     3          27       0.0166259           0.125     Successful search (ES-ell)        
     3          28      0.00797168           0.125     Incremental search (ES-ell)        
     3          38      

{'fun': <bound method simulation.objective_bads of simulation(n_stud=20000, prop_gp=[0.4, 0.6], mean_gp=[0, 0], std_gp=[2, 2], n_col=2, noise_mean=[0, 0], noise_std=[2, 2], prop_all_g_prefer=[0.4, 0.4], capacities_rate=[0.2, 0.2], noise_cov=[1, 0.5], students=[array([ 0.75130899, -0.76892244, -0.24943529, ...,  1.56905453,
        -0.34482515, -2.03198628]), array([-1.5278379 , -0.31930495,  0.08134665, ...,  2.04996579,
        -2.84922625, -1.82525685])], grade_estimate_gr=[array([[ 5.38506362,  6.65149139],
        [ 2.10306378,  1.8443918 ],
        [ 0.96497709, -0.59322929],
        ...,
        [ 0.53518572, -0.67508482],
        [-1.16301546, -1.30490066],
        [-2.57953439, -2.56334289]]), array([[-2.48116783, -1.95772526],
        [-0.35102368, -1.37633214],
        [ 2.13209638, -3.47855   ],
        ...,
        [ 5.64740839,  2.66620499],
        [-2.18758091, -2.78005776],
        [-0.64070682, -0.51367409]])], grade_estimate_col=[[[5.385063618823559, 2.103063780434730

In [11]:
solver.print_result()

BADS minimum at: x_min = [1.72709466 0.68814529], fval = 0.0002823
total f-count: 95, time: 101.08 s


(array([1.72709466, 0.68814529]), np.float64(0.00028229125882844874))