In [1]:
from util import *

In [2]:
import numpy as np

#Parameter to create student
n_stud = 20000
prop_gp = [0.4,0.6] #vector gamma in the paper
mean_gp = [0,0]
chi = [2,2] #std of latent qualities of groups

#Parameter of college
n_col = 2 #Number of college
noise_mean = [0,0]
sigma = [2,2] #std of noise of each groups
lambdas = [1,0.5] #cov of noies of each groups
prop_all_g_prefer = [0.4,0.4] #This should be the vector beta in the paper

capacities_rate = [0.2,0.2] #This should be the vector alpha in the paper.
capacities = [int(r * n_stud) for r in capacities_rate]#This vector must have the same length as the number of college, i.e. len(capacities) = n_col. The componenets should be integers

sigma_i = np.sqrt(chi[0]**2 + sigma[0]**2)
sigma_ii = np.sqrt(chi[1]**2 + sigma[1]**2)
cor_i = chi[0]**2/sigma_i**2
cor_ii = chi[1]**2/sigma_ii**2
std_estimated = [np.sqrt(i**2 + j**2) for i,j in zip(chi,sigma)]

In [3]:
simul = simulation(n_stud = n_stud,
                   prop_gp=prop_gp,
                   mean_gp=mean_gp,
                   std_gp = chi,
                   n_col=n_col,
                   noise_mean=noise_mean,
                   noise_std = sigma,
                   noise_cov = lambdas,
                   prop_all_g_prefer=prop_all_g_prefer,
                   capacities_rate=capacities_rate)

In [4]:
simul.create_students()

[array([-1.88281339,  1.57107918,  2.64377081, ..., -2.89704505,
        -0.83291343,  2.37250056]),
 array([-3.97291032, -2.08991677, -2.22648882, ..., -2.52417639,
         3.18837713,  0.81097557])]

In [5]:
simul.create_col_estim_corr_nois()

[array([[-3.00171217, -1.43067831],
        [ 3.76836491,  0.0191694 ],
        [ 2.11046919,  3.5511099 ],
        ...,
        [-4.06485852, -2.72482593],
        [-0.19743828,  0.69331714],
        [ 2.54689032,  3.84922234]]),
 array([[-3.99311617, -3.11702603],
        [ 0.20012989, -0.68947583],
        [-1.43598101, -4.14777255],
        ...,
        [-1.68927768, -5.20102283],
        [ 4.27524326,  3.94176118],
        [ 5.16309724,  1.36437332]])]

In [6]:
simul.create_stud_pref_2()

[[[1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [0, 1],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [0, 1],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],
  [0, 1],
  [1, 0],
  [1, 0],
  [1, 0],


In [7]:
simul.grades_gr_to_grades_col()

[[[-3.0017121749245628,
   3.768364912067671,
   2.1104691859333893,
   1.0772369455860025,
   2.119469972417187,
   2.566898105565959,
   -0.7869519692562159,
   3.2074133205445987,
   -1.0354909646321198,
   -2.2793959045794217,
   1.1437390315127727,
   2.491137450600292,
   0.8961463943376251,
   3.1699209011586236,
   1.2424403213876603,
   0.5864765436660826,
   1.1333066747157439,
   -2.118191415178125,
   0.9785392315020455,
   0.5684997302598178,
   -4.206494932872587,
   2.245312415891169,
   -5.876808089197043,
   -1.884240514607996,
   -2.145918722147753,
   -0.4459273284653585,
   -1.1658476399735704,
   1.6495956749915066,
   4.689643245633664,
   4.2988478685760105,
   -2.0254677980389344,
   1.9227577907758757,
   1.556436246008133,
   -4.060587544031421,
   3.1350723656450605,
   1.0179749772214335,
   -1.495925035561381,
   -0.7783281494519618,
   -0.11747045382175159,
   0.2713663802102908,
   -3.3469724401608323,
   2.6003849755039785,
   4.425317899767238,
   -0.70

In [8]:
simul.grades_gr_to_grades_col()

[[[-3.0017121749245628,
   3.768364912067671,
   2.1104691859333893,
   1.0772369455860025,
   2.119469972417187,
   2.566898105565959,
   -0.7869519692562159,
   3.2074133205445987,
   -1.0354909646321198,
   -2.2793959045794217,
   1.1437390315127727,
   2.491137450600292,
   0.8961463943376251,
   3.1699209011586236,
   1.2424403213876603,
   0.5864765436660826,
   1.1333066747157439,
   -2.118191415178125,
   0.9785392315020455,
   0.5684997302598178,
   -4.206494932872587,
   2.245312415891169,
   -5.876808089197043,
   -1.884240514607996,
   -2.145918722147753,
   -0.4459273284653585,
   -1.1658476399735704,
   1.6495956749915066,
   4.689643245633664,
   4.2988478685760105,
   -2.0254677980389344,
   1.9227577907758757,
   1.556436246008133,
   -4.060587544031421,
   3.1350723656450605,
   1.0179749772214335,
   -1.495925035561381,
   -0.7783281494519618,
   -0.11747045382175159,
   0.2713663802102908,
   -3.3469724401608323,
   2.6003849755039785,
   4.425317899767238,
   -0.70

In [9]:
solver = solver()

In [10]:
solver.cutoff_solver(simul.objective_bads)

Beginning optimization of a DETERMINISTIC objective function

 Iteration    f-count         f(x)           MeshScale          Method             Actions
     0           2        0.195788               1                                 Uncertainty test
     0           6        0.195788               1         Initial mesh            Initial points
     0          10        0.195788             0.5         Refine grid             Train
     1          13        0.175102             0.5     Incremental search (ES-wcm)        
     1          18        0.175102            0.25         Refine grid             Train
     2          19        0.094107            0.25     Incremental search (ES-ell)        
     2          22         0.08916            0.25     Incremental search (ES-ell)        
     2          26         0.08916           0.125         Refine grid             
     3          27       0.0681936           0.125     Incremental search (ES-wcm)        
     3          28     

{'fun': <bound method simulation.objective_bads of simulation(n_stud=20000, prop_gp=[0.4, 0.6], mean_gp=[0, 0], std_gp=[2, 2], n_col=2, noise_mean=[0, 0], noise_std=[2, 2], prop_all_g_prefer=[0.4, 0.4], capacities_rate=[0.2, 0.2], noise_cov=[1, 0.5], students=[array([-1.88281339,  1.57107918,  2.64377081, ..., -2.89704505,
        -0.83291343,  2.37250056]), array([-3.97291032, -2.08991677, -2.22648882, ..., -2.52417639,
         3.18837713,  0.81097557])], grade_estimate_gr=[array([[-3.00171217, -1.43067831],
        [ 3.76836491,  0.0191694 ],
        [ 2.11046919,  3.5511099 ],
        ...,
        [-4.06485852, -2.72482593],
        [-0.19743828,  0.69331714],
        [ 2.54689032,  3.84922234]]), array([[-3.99311617, -3.11702603],
        [ 0.20012989, -0.68947583],
        [-1.43598101, -4.14777255],
        ...,
        [-1.68927768, -5.20102283],
        [ 4.27524326,  3.94176118],
        [ 5.16309724,  1.36437332]])], grade_estimate_col=[[[-3.0017121749245628, 3.7683649120676

BADS minimum at: x_min = [1.76308658 0.66786794], fval = 0.00077
total f-count: 111, time: 137.25 s


(array([1.76308658, 0.66786794]), np.float64(0.0007699638621752047))

In [12]:
simul.bayes_update_grade()

[[[-3.0017121749245628,
   3.768364912067671,
   2.1104691859333893,
   1.0772369455860025,
   2.119469972417187,
   2.566898105565959,
   -0.7869519692562159,
   3.2074133205445987,
   -1.0354909646321198,
   -2.2793959045794217,
   1.1437390315127727,
   2.491137450600292,
   0.8961463943376251,
   3.1699209011586236,
   1.2424403213876603,
   0.5864765436660826,
   1.1333066747157439,
   -2.118191415178125,
   0.9785392315020455,
   0.5684997302598178,
   -4.206494932872587,
   2.245312415891169,
   -5.876808089197043,
   -1.884240514607996,
   -2.145918722147753,
   -0.4459273284653585,
   -1.1658476399735704,
   1.6495956749915066,
   4.689643245633664,
   4.2988478685760105,
   -2.0254677980389344,
   1.9227577907758757,
   1.556436246008133,
   -4.060587544031421,
   3.1350723656450605,
   1.0179749772214335,
   -1.495925035561381,
   -0.7783281494519618,
   -0.11747045382175159,
   0.2713663802102908,
   -3.3469724401608323,
   2.6003849755039785,
   4.425317899767238,
   -0.70

In [16]:
cutoff_values,_ = solver.print_result()
count = welfare(simul.stud_pref,simul.updated_grade_estimate_col,cutoff_values)

BADS minimum at: x_min = [1.76308658 0.66786794], fval = 0.00077
total f-count: 111, time: 137.25 s


In [17]:
count.student_by_col()

Number of student admitted to college 1 in group 0: 1549
Number of student admitted to college 2 in group 0: 1555
Number of student admitted to college 1 in group 1: 2462
Number of student admitted to college 2 in group 1: 2453
4011 4008


(4011, 4008)